import os
from scrapli.driver.core import (
    AsyncEOSDriver,
    AsyncIOSXEDriver,
    AsyncJunosDriver,
    AsyncNXOSDriver,
)



DEVICES = [
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.101",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncIOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.102",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncIOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.103",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncIOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.104",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncIOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.105",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncIOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.106",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncIOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.111",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncNXOSDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.112",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncNXOSDriver,
    },
        {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.113",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncNXOSDriver,
    },
        {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.114",
        "port": 22,
        "transport": "asyncssh",
        "auth_strict_key": False,
        "driver": AsyncNXOSDriver,
    },
]
