#!/usr/bin/env python

from scrapli.driver.core import (
    EOSDriver,
    IOSXEDriver,
    JunosDriver,
    NXOSDriver,
)

switches = [
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.101",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": IOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.102",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": IOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.103",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": IOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.104",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": IOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.105",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": IOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.106",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": IOSXEDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.111",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": NXOSDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.112",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": NXOSDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.113",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": NXOSDriver,
    },
    {
        "auth_username": "admin",
        "auth_password": "Stefan2020",
        "host": "172.16.1.114",
        "port": 22,
        "transport": "paramiko",
        "auth_strict_key": False,
        "driver": NXOSDriver,
    },
]
